Feature/ast 12643 sca panel
Checkmarx/ast-jetbrains-plugin pull request #114
Opened 2022-07-26 16:02 UTC by AndreGCX

By submitting a PR to this repository, you agree to the terms within the [Checkmarx Code of Conduct](../docs/code_of_conduct.md). Please see the [contributing guidelines](../docs/contributing.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change.

### References

> Include supporting link to GitHub Issue/PR number

### Testing

> Describe how this change was tested. Be specific about anything not tested and reasons why. If this solution has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR (if applicable).
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used

2022-07-26 16:27 UTC, diogopcx requested changes

2022-07-26 16:27 UTC, diogopcx commented on src/main/resources/messages/CxBundle.properties
> +ADVISORY=Advisory
Is ADVISORY used?

2022-07-26 16:27 UTC, diogopcx commented on src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java
> +    private  JPanel buildScaPanel(Result result, @NotNull Runnable runnableDraw, Runnable runnableUpdater) {
We need to simplify this method.

2022-07-26 16:27 UTC, diogopcx commented on src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java
> +            System.out.println("NOT SCA");
Is this something we should log or left over?

2022-07-26 16:27 UTC, diogopcx commented on src/main/java/com/checkmarx/intellij/Constants.java
> +    public static final String HTML_FONT_BLUE_FORMAT = "<html><font color='#2C7AE4'>%s</font></html>";
Do these constants work with different themes?

2022-08-31 14:23 UTC, pedrompflopes approved these changes

2022-08-31 14:24 UTC, merged